### PR TITLE
Implemented picture-in-picture feature

### PR DESCRIPTION
**Pull request by em92**
Demo: https://www.youtube.com/watch?v=3ynQ4oMCjD4
Added cvars: https://imgur.com/i9GbQZE

### CODE REVIEW

**Comment by entdark** [comment]
Good old multi POV.
You did it a bit wrong though. No need to modify the engine and send extra refdef_t.
Calling trap_R_RenderScene again with another refdef_t from cgame is enough.
That's how they drew 3D heads in HUD in Q3A.
So it's even possible to draw as many POVs as you wish, instead of just 2.

I did something similar:
https://gist.github.com/entdark/9f076d832ac268108b7fa9d1a52281a6
You can create up to 4 POV windows in each corner with a GUI and commands instead of cvars.

**Comment by em92** [comment]
> Good old multi POV.

I am not intending to make extra player povs. Just "camera" with viewport.

> You did it a bit wrong though. No need to modify the engine and send extra refdef_t.
> Calling trap_R_RenderScene again with another refdef_t from cgame is enough.
> That's how they drew 3D heads in HUD in Q3A.

No, it is not enough. It renders map, but not entities. I guess 'cos they are not added to the new scene. In your code they are added on lines 302-321 before rendering on line 346. 3d heads are added as entity to the scene, then it renders the scene. Also I am not sure that adding lines like in mentioned 302-321 is enough. That method that I wrote is working as ingame portals/mirrors, which is enough for "camera" with viewport.

**Comment by entdark** [comment]
You can ignore any entity as well.
And it can be free cameras as well, no need to stick to players, I just showed an example that how it was designed to be worked with.
And your need can be done without engine modification - just rerender the scene w/o entities on any coordinate with any angles, with any fov.
The solutions should always be generic if possible instead of hardcoded.
Your solution can please some users, but the others would like to have actually a POV, another ones - several windows etc.
So if possible to make it generic then why not?
Shortly, all you want can be done fully on cgame side and more generic to please the most.

**Comment by em92** [comment]
Will rewrite as you suggested

**Pull request closed without merging**
